# TODO при создании контейнера файл выложить в корневой каталог
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8002:5000"
    command: python3 start.py
    volumes:
      - .:/Book
    environment:
      - DB_HOST=postgres_container
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    hostname: postgres_container
