"""2

Revision ID: 07151c6e7f3c
Revises: 07fab73a63a1
Create Date: 2023-08-11 09:28:05.328079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07151c6e7f3c'
down_revision: Union[str, None] = '07fab73a63a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('genre', sa.Text(), nullable=True))
    op.drop_column('content', 'id_genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('id_genre', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('content', 'genre')
    # ### end Alembic commands ###
